// Public development and preview builds use open-source Font Awesome icons.
// Production resolves the original Sharp imports to the licensed packages.
export {
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faArrowsRotate,
  faBars,
  faBookOpen,
  faBookmark,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleInfo,
  faCircleQuestion,
  faCode,
  faCompass,
  faCopy,
  faCrosshairs,
  faDatabase,
  faDownload,
  faFillDrip,
  faFire,
  faFlask,
  faFolderOpen,
  faGauge,
  faGaugeHigh,
  faHand,
  faHouseChimney,
  faLayerGroup,
  faLightbulb,
  faLink,
  faMagnifyingGlass,
  faMapLocationDot,
  faMousePointer,
  faPalette,
  faPenToSquare,
  faPlay,
  faPlus,
  faRotateLeft,
  faRoute,
  faSliders,
  faTags,
  faTrash,
  faTriangleExclamation,
  faWandMagicSparkles,
  faXmark,
  faArrowRight as faArrowUpRight,
  faKeyboard as faCommand,
  faCircle as faCircleDashed,
  faCircle as faCircleSmall,
  faGlobe as faGlobePointer,
  faTableCells as faGrid,
  faTableCellsLarge as faGrid2,
  faSatelliteDish as faRadar,
  faScroll as faScrollOld,
  faWandMagicSparkles as faSparkles,
  faSpinner as faSpinnerThird,
  faStar as faStars,
} from '@fortawesome/free-solid-svg-icons';
