import type { GlobeKind, ThemePresetName } from '@globiojs/core';
import type {
  ActiveLayer,
  ConfiguratorState,
  GlobeSettings,
  HeatmapSettings,
  HeatmapSurfaceMode,
} from './types';
import { defaultArcSettings, defaultMarkerSettings } from './layer-fixtures';

export const defaultGlobeSettings: GlobeSettings = {
  kind: 'cinematic',
  theme: 'cinematic-night',
  countryResolution: 'low',
  hoverEnabled: true,
  hoverOccludeBackSide: true,
  // Empty string / 0 numeric = "use theme token" sentinel — leaves
  // outline-dark's cyan-tinted hover stroke + glow palette intact
  // until the user explicitly overrides via the Selection card.
  hoverStrokeColor: '',
  hoverStrokeWidth: 0,
  hoverStrokeOpacity: 0,
  hoverGlowColor: '',
  hoverGlowWidth: 0,
  hoverGlowOpacity: 0,
  activeStrokeColor: '',
  activeStrokeWidth: 0,
  activeStrokeOpacity: 0,
  // Country fill — 'none' default keeps the layer hidden until the
  // user picks a mode in the Country fill workshop card or the
  // choropleth data layer fires `setData`. Other defaults are
  // sentinels (empty / 0) so flipping mode picks up the theme tokens.
  // Empty string / 0 means "use theme token" (`countries.fill.defaultColor` /
  // `.opacity`), so enabling the layer later stays in sync with whichever
  // theme the user picked.
  countryFillMode: 'none',
  countryFillDefaultColor: '',
  countryFillDefaultOpacity: 0,
  // Curated palette for the demo's 'palette' mode. Picked so the
  // hue spread reads cleanly on the dark globe — neighbouring
  // countries land on visually distinct entries.
  countryFillPalette: [
    '#67e8f9',
    '#fbbf24',
    '#f472b6',
    '#34d399',
    '#a78bfa',
    '#fb923c',
    '#22d3ee',
    '#facc15',
  ],
  countryFillHoverColor: '',
  countryFillHoverOpacity: 0,
  countryFillActiveColor: '',
  countryFillActiveOpacity: 0,
  // Dotted-only: per-country dot tint. 'theme' defers to the dotted
  // theme colour for every dot (no per-country override). Palette
  // mirrors the country-fill default so flipping just dots-mode to
  // 'palette' produces a coherent tinted globe.
  dottedDotsMode: 'theme',
  dottedDotsPalette: [
    '#67e8f9',
    '#fbbf24',
    '#f472b6',
    '#34d399',
    '#a78bfa',
    '#fb923c',
    '#22d3ee',
    '#facc15',
  ],
  dottedDotsHoverColor: '',
  dottedDotsActiveColor: '',
  countryLabels: false,
  // High threshold by design — only the ~10-15 biggest countries
  // (Russia, Canada, Brazil, USA, China, Australia, India, …) read
  // labels at the boot zoom. Once the user zooms in, smaller ones
  // fade in. Keeps the first-impression frame clean.
  labelMinScreenSize: 300,
  labelSizeFadeRange: 0.5,
  labelTransitionMs: 240,
  // Soft white halo at low radius — readable on the dark ocean
  // without the loud cyan glow the previous default produced.
  labelHaloEnabled: true,
  labelHaloRadius: 1.5,
  labelHaloColor: 'rgba(0, 8, 20, 0.85)',
  labelHaloSteps: 4,
  labelColor: '',
  labelFontSize: 11,
  labelFontWeight: '400',
  autoRotate: true,
  autoRotateSpeed: 0.06,
  axisTilt: 23.5,
  atmosphere: false,
  atmosphereColor: '',
  atmosphereIntensity: 0,
  atmosphereRadiusScale: 0,
  atmospherePower: 0,
  atmosphereThreshold: 0.6,
  atmosphereSide: 'back',
  atmosphereBlending: 'additive',
  // Very slow atmospheric breath — the limb halo barely shifts. Period
  // ~6s, amplitude only ~10% of base intensity, so the user might not
  // notice it consciously but the globe never reads "frozen still".
  atmospherePulse: true,
  atmospherePulseSpeed: 0.14,
  atmospherePulseAmplitude: 0.1,
  starfield: true,
  starfieldDensity: 2400,
  starfieldSize: 1.5,
  starfieldSizeVariety: 0.55,
  starfieldMultiColor: true,
  // Cinematic mostly-cool palette with two warm accents — most stars
  // sit in the white/icy-blue family of the theme, occasional warm
  // pinpricks keep it from going monochrome.
  starfieldPalette: ['#ffffff', '#e9f1ff', '#cfdcff', '#b9c8ff', '#7fb6ff', '#fff4d6', '#ffd4a8'],
  starfieldTwinkle: true,
  starfieldTwinkleIntensity: 0.55,
  starfieldTwinkleSpeed: 0.4,
  focusPulse: true,
  focusPulseOrigin: 'click',
  focusPulseOnSurfaceClick: true,
  outlinePulseDurationMs: 1600,
  outlinePulseRadiusBase: 0.07,
  outlinePulseAngularBand: 0.015,
  outlinePulseScaleMin: 0.4,
  outlinePulseScaleMax: 2.8,
  outlinePulseOpacity: 1,
  outlinePulseSegments: 128,
  outlinePulseColor: '',
  outlinePulseRadiusFactor: 1.0045,
  outlineHoverLift: 0,
  outlineHoverGlowLift: 0.0035,
  outlineHoverGlowEnabled: true,
  // Continent dim default-on — hovering a country drops the *other*
  // continents' borders to ~35% so the active region foregrounds and
  // the eye snaps to it. Subtle but a huge perceptual focus boost.
  outlineContinentDim: true,
  outlineContinentDimAmount: 0.35,
  outlineHoverCrosshair: true,
  outlineHoverCrosshairColor: '',
  outlineHoverCrosshairSize: 0.014,
  outlineHoverCrosshairOpacity: 0.9,
  outlineHoverCrosshairRingRadiusFactor: 0.75,
  outlineHoverCrosshairCardinalTicks: true,
  outlineHoverCrosshairTooltip: true,
  outlineHoverCrosshairTooltipDecimals: 2,
  ...defaultArcSettings,
  ...defaultMarkerSettings,
  arcColor: '#f6b44d',
  arcWidth: 1.25,
  arcMinHeight: 0.18,
  arcMaxHeight: 0.72,
  markerDataset: 'megacities',
  markerSize: 0.85,
  markerHoverScale: 1.45,
  markerColor: '#ffd36a',
  markerPerMarkerColor: false,
  markerPulseAmplitude: 0.18,
  // Dotted defaults — empty-string colors / 0 numerics mean "use theme
  // default" sentinel; sensible booleans default-on so the workshop's
  // baseline preview shows the dot field at full personality.
  dottedColor: '',
  dottedSizeScale: 1,
  dottedOpacity: 0,
  dottedRipple: true,
  dottedRippleBoost: 1.5,
  dottedRippleSpeed: 1.2,
  dottedRippleWidth: 0.18,
  dottedRippleMaxConcurrent: 3,
  dottedRippleColor: '',
  dottedFlash: true,
  dottedFlashStrength: 2,
  dottedFlashDecay: 4,
  dottedFlashColor: '',
  dottedDrift: true,
  dottedDriftAmplitude: 0.15,
  dottedDriftSpeed: 0.4,
  dottedDriftFreq: 3,
  dottedDriftAxis: 'ns',
  dottedDriftPerCountryPhase: true,
  dottedHoverDots: true,
  dottedHoverScale: 1.3,
  dottedHoverBrightnessBoost: 0.7,
  dottedHoverDuration: 0.25,
  dottedCursorWake: true,
  dottedCursorWakeAmplitude: 0.6,
  dottedCursorWakeFade: 0.45,
  dottedCursorWakeWidth: 0.09,
  dottedLatitudeBands: false,
  dottedEquatorBoost: 0.35,
  dottedTropicsBoost: 0.18,
  dottedLatitudeBandWidth: 4,
  dottedPulseBreath: false,
  dottedPulseBreathAmplitude: 0.12,
  dottedPulseBreathSpeed: 0.35,
  dottedConstellation: false,
  dottedConstellationColor: '',
  dottedConstellationOpacity: 0.55,
  dottedConstellationDistanceFactor: 1.6,
  // Hover lift defaults to a subtle ~0.8% radial bump; bigger reads as
  // a cinematic country pop-out.
  dottedHoverLift: 0.008,
  // Pinned-country pulse default-on so the workshop's preview shows
  // the visual the moment the user clicks a country to pin it.
  dottedActiveCountry: true,
  dottedActiveBoost: 0.65,
  dottedActiveScale: 1.18,
  dottedActivePulseSpeed: 0.65,
  dottedActiveLift: 0.012,
  // Edge highlight default-on — the dotted analogue of the standard
  // country highlight stroke that dotted opted out of. Picks up the
  // existing surface dots that already trace the boundary.
  dottedEdgeHighlight: true,
  dottedEdgeBoost: 0.55,
  dottedEdgeLift: 0.004,
  // Hologram defaults — picked to match the existing tokens' look so the
  // user opens the preset and sees the same projection they'd get with a
  // bare `kind: 'hologram'`. Every numeric default-of-0 = "use theme
  // default" sentinel that the core layer interprets as "leave alone".
  hologramScanlines: true,
  hologramScanlineSpeed: 0,
  hologramScanlineDensity: 0,
  hologramScanlineOpacity: 0.4,
  hologramScanlineDirection: 'horizontal',
  hologramRimGlow: true,
  hologramRimColor: '',
  hologramRimIntensity: 0,
  hologramRimWidth: 2,
  hologramGlitch: true,
  hologramGlitchIntervalMin: 4,
  hologramGlitchIntervalMax: 9,
  hologramGlitchAmplitude: 0,
  hologramGlitchChannelShift: 0.5,
  hologramOuterGlow: true,
  hologramOuterGlowColor: '',
  hologramOuterGlowSpread: 1.02,
  hologramOuterGlowIntensity: 0,
  hologramChromaticAberration: true,
  hologramChromaticAberrationAmount: 0.45,
  hologramChromaticAberrationMode: 'rim',
  hologramNoise: true,
  hologramNoiseIntensity: 0.18,
  hologramNoiseScale: 1.6,
  hologramNoiseSpeed: 22,
  hologramProjectorPulse: true,
  hologramProjectorPulseSpeed: 0.35,
  hologramProjectorPulseAmplitude: 0.6,
  hologramProjectorPulseColor: '',
  hologramDataScan: true,
  hologramDataScanSpeed: 0.2,
  hologramDataScanWidth: 0.05,
  hologramDataScanOpacity: 0.7,
  hologramDataScanAxis: 'horizontal',
  hologramDataScanColor: '',
  hologramPhaseShimmer: false,
  hologramPhaseShimmerScale: 60,
  hologramPhaseShimmerIntensity: 0.12,
  hologramPhaseShimmerSpeed: 0.4,
  hologramCalibrationTicks: false,
  hologramCalibrationTicksCount: 36,
  hologramCalibrationTicksLength: 0.04,
  hologramCalibrationTicksOpacity: 0.9,
  hologramPulseDurationMs: 1050,
  hologramPulseRadiusBase: 0.075,
  hologramPulseAngularBand: 0.017,
  hologramPulseScaleMin: 0.22,
  hologramPulseScaleMax: 2.9,
  hologramPulseOpacity: 1.35,
  hologramPulseSegments: 128,
  hologramPulseColor: '',
  hologramPulseRadiusFactor: 1.012,
  // Cinematic defaults — first-run hero setup for the new marketing-grade
  // globe. Empty-string colors inherit the cinematic-night theme.
  cinematicOceanColor: '',
  cinematicLandColor: '',
  cinematicCloudColor: '',
  cinematicNightColor: '',
  cinematicLightX: -0.62,
  cinematicLightY: 0.55,
  cinematicLightZ: 0.55,
  cinematicLightingMode: 'hero',
  cinematicTerminatorSoftness: 0.42,
  cinematicTerminatorContrast: 1.45,
  cinematicKeyIntensity: 1.6,
  cinematicFillIntensity: 0.1,
  cinematicRimColor: '',
  cinematicRimIntensity: 1.42,
  cinematicRimPower: 2.55,
  cinematicSpecularIntensity: 0.95,
  cinematicOceanSheen: 0.62,
  cinematicBorders: true,
  cinematicBorderColor: '',
  cinematicBorderIntensity: 0,
  cinematicCityLights: false,
  cinematicCityLightColor: '',
  cinematicCityLightIntensity: 1.55,
  cinematicCityLightCount: 11500,
  cinematicCityLightSize: 0.0058,
  cinematicCityLightTwinkle: true,
  cinematicNetwork: true,
  cinematicNetworkColor: '',
  cinematicNetworkOpacity: 0.22,
  cinematicNetworkConnections: 56,
  cinematicNetworkPulseSpeed: 0.28,
  cinematicQuality: 'auto',
  cinematicLightInfluence: 1,
  cinematicCameraInfluence: 1,
  cinematicDensityInfluence: 1,
  cinematicTerminatorBoost: 1.32,
  cinematicHorizonGlow: 1.30,
  cinematicAtmosphericScatter: 1.35,
  cinematicSurfaceMicroDetail: 1.18,
  cinematicCityNightResponse: 0,
  cinematicOrbitalFlow: 1.0,
  cinematicPulseDurationMs: 1350,
  cinematicPulseRadiusBase: 0.075,
  cinematicPulseAngularBand: 0.015,
  cinematicPulseScaleMin: 0.32,
  cinematicPulseScaleMax: 2.7,
  cinematicPulseOpacity: 1.1,
  cinematicPulseSegments: 128,
  cinematicPulseColor: '',
  cinematicPulseRadiusFactor: 1.01,
  // Sun rig — 'fixed' keeps the marketing terminator parked where the
  // light-direction sliders put it. 'orbit'/'realtime' animate it.
  cinematicSunMode: 'fixed',
  cinematicSunSpeed: 6,
  cinematicSunTimeScale: 1,
  cinematicSunVisible: true,
  cinematicSunGlare: 1,
  cinematicSunSize: 1,
  cinematicSunColor: '',
  // Cloud shell above the surface.
  cinematicClouds: true,
  cinematicCloudCoverage: 0.42,
  cinematicCloudShellOpacity: 0.72,
  cinematicCloudSpeed: 1,
  cinematicCloudSoftness: 0.5,
  cinematicCloudShadows: true,
  cinematicCloudShadowStrength: 0.45,
  cinematicCloudAltitude: 0.009,
  // Surface realism — relief, biomes, shallows, moonlight, snow line.
  cinematicRelief: 1,
  cinematicBiomes: true,
  cinematicShallows: 0.6,
  cinematicMoonlight: 1,
  cinematicSnowLine: 0.72,
  cinematicIceColor: '',
  cinematicVegetationColor: '',
  cinematicDesertColor: '',
  cinematicShallowWaterColor: '',
  // Night-side auroral curtains.
  cinematicAurora: true,
  cinematicAuroraIntensity: 0.8,
  cinematicAuroraSpeed: 1,
  cinematicAuroraLatitude: 68,
  cinematicAuroraColor: '',
  cinematicAuroraTopColor: '',
  // Scattering shell tuning.
  cinematicScatter: 1,
  cinematicMie: 1,
  cinematicAirglow: 0.18,
  cinematicAtmosphereThickness: 0.075,
  // Procedural by default — the 2k Earth maps are opt-in.
  cinematicTextures: 'none',
  // Milky Way band (cinematic starfield only).
  cinematicMilkyWay: true,
  cinematicMilkyWayIntensity: 0.55,
  // Shared HDR post-processing pipeline.
  postfxEnabled: true,
  postfxExposure: 1,
  postfxBloomStrength: 0.48,
  postfxBloomThreshold: 0.8,
  postfxBloomRadius: 0.6,
  postfxStreak: 0.22,
  postfxVignette: 0.32,
  postfxChromatic: 0.0025,
  postfxGrain: 0.035,
  // Paper kind defaults — textured, colorful atlas look: rich enough for
  // education / science demos without becoming an antique-only sepia map.
  paperSurfaceColor: '',
  paperSurfaceNoise: 0.11,
  paperSurfaceVignette: 0.22,
  paperSurfaceFibers: 0.58,
  paperSurfaceStains: 0.28,
  paperSurfaceWashColor: '#7faeac',
  paperSurfaceWaterLines: 0.58,
  paperSurfaceWaterLineColor: '#567f80',
  paperBorders: true,
  paperBorderColor: '',
  paperBorderOpacity: -1,
  paperBorderWidth: 1.35,
  paperBorderRoughness: 0.2,
  paperStipple: true,
  paperStippleDensity: 2.4,
  paperStippleSize: 0.9,
  paperInkBleed: true,
  paperInkBleedColor: '',
  paperInkBleedOpacity: 0.3,
  paperInkBleedSpread: 0.0008,
  paperFill: true,
  paperFillColor: '',
  paperFillOpacity: 0.84,
  paperFillMode: 'pastel',
  paperGrid: true,
  paperGridColor: '',
  paperGridOpacity: -1,
  paperGridStep: 15,
  paperGridMajorEvery: 3,
  paperGridMajorOpacity: -1,
  paperSepia: true,
  paperSepiaColor: '#8b6f47',
  paperSepiaOpacity: 0.12,
  paperVignette: true,
  paperVignetteColor: '#3a2a14',
  paperVignetteIntensity: 0.28,
  paperVignetteRadius: 0.46,
  paperCompass: true,
  paperCompassLat: 32,
  paperCompassLng: -38,
  paperCompassColor: '#5b3a1f',
  paperCompassOpacity: 0.48,
  paperCompassSize: 7.5,
  paperAging: true,
  paperAgingCount: 18,
  paperAgingColor: '#7a5a2c',
  paperAgingIntensity: 0.18,
  paperAgingSeed: 1,
  paperWatermark: false,
  paperWatermarkText: 'ATLAS',
  paperWatermarkColor: '#5b3a1f',
  paperWatermarkOpacity: 0.18,
  paperWatermarkSize: 28,
  paperWatermarkPosition: 'bottomRight',
  paperPulseDurationMs: 1550,
  paperPulseRadiusBase: 0.065,
  paperPulseAngularBand: 0.022,
  paperPulseScaleMin: 0.28,
  paperPulseScaleMax: 2.35,
  paperPulseOpacity: 0.62,
  paperPulseSegments: 112,
  paperPulseColor: '',
  paperPulseRadiusFactor: 1.006,
  /* ───────── Wireframe defaults ───────── */
  wireframeColor: '',
  wireframeOpacity: 0,
  wireframeDensity: 1,
  wireframePulse: 0,
  wireframePulseSpeed: 0.5,
  wireframeHierarchy: true,
  wireframeHierarchyMajorStepDeg: 30,
  wireframeHierarchyMajorBoost: 1.6,
  wireframeHierarchyMinorBoost: 0.85,
  wireframeClickPulse: true,
  wireframeClickPulseColor: '',
  wireframeClickPulseSpeed: 1.5,
  wireframeClickPulseWidth: 0.18,
  wireframeClickPulseBoost: 2.5,
  wireframeClickPulseMaxConcurrent: 4,
  wireframeEmphasis: true,
  wireframeEmphasisStrongColor: '',
  wireframeEmphasisWeakColor: '',
  wireframeEmphasisStrongOpacity: 0,
  wireframeEmphasisWeakOpacityFactor: 0.5,
  wireframeEquatorBeam: true,
  wireframeEquatorBeamColor: '',
  wireframeEquatorBeamOpacity: 0.85,
  wireframeEquatorBeamPulse: true,
  wireframeEquatorBeamPulseSpeed: 0.6,
  wireframeGlitch: true,
  wireframeGlitchIntervalMin: 5,
  wireframeGlitchIntervalMax: 15,
  wireframeActiveRing: true,
  wireframeActiveRingColor: '',
  wireframeActiveRingOpacity: 0,
  wireframeActiveRingPadding: 1.2,
  wireframeActiveRingRotationSpeed: 0.5,
  wireframePoleStreams: true,
  wireframePoleStreamsColor: '',
  wireframePoleStreamsOpacity: 0,
  wireframePoleStreamsCount: 16,
  wireframePoleStreamsSpeed: 0.6,
  wireframePoleStreamsSize: 0,
  wireframeDataPackets: true,
  wireframeDataPacketsColor: '',
  wireframeDataPacketsCount: 24,
  wireframeDataPacketsSpeed: 0.9,
  wireframeDataPacketsTrail: 0.18,
  wireframeDataPacketsSize: 0.018,
  wireframeDataPacketsAxis: 'both',
  wireframeCompass: true,
  wireframeCompassColor: '',
  wireframeCompassSize: 0.075,
  wireframeCompassOpacity: 0.9,
  wireframeCompassPoles: true,
  wireframeGridPulse: false,
  wireframeGridPulseColor: '',
  wireframeGridPulseIntervalSec: 4,
  wireframeGridPulseSpeed: 1.2,
  wireframeGridPulseWidth: 0.16,
  wireframeGridPulseBoost: 1.8,
  wireframeGridPulseMode: 'fixed',
  wireframeGridPulseOriginLat: 0,
  wireframeGridPulseOriginLng: 0,
  wireframePolePulse: false,
  wireframePolePulseColor: '',
  wireframePolePulseIntervalSec: 5,
  wireframePolePulseSpeed: 1,
  wireframePolePulseBoost: 1.5,
  wireframePolePulseWhich: 'both',
  clickToFocus: true,
  focusPadding: 0.15,
  focusDurationMs: 1500,
  focusElevation: 0,
  focusPauseAutoRotate: true,
  zoomMode: 'attract',
  zoomStrength: 0.7,
  smoothZoom: true,
  minZoom: 1.25,
  maxZoom: 7.5,
  initialLat: 32,
  initialLng: -66,
  pixelRatio: 'auto',
  adaptiveQuality: true,
  antialias: true,
  maxFps: 60,
};

export const defaultThemeForKind: Record<GlobeKind, ThemePresetName> = {
  cinematic: 'cinematic-night',
  outline: 'outline-dark',
  dotted: 'dotted-dark',
  wireframe: 'wireframe-tron',
  paper: 'paper-default',
  hologram: 'hologram-cyan',
};

export const globeDefaultsForKind = (kind: GlobeKind): Partial<GlobeSettings> => {
  const base = {
    kind,
    theme: defaultThemeForKind[kind],
    atmosphere: kind !== 'cinematic',
    countryLabels: kind !== 'cinematic',
  };
  if (kind === 'cinematic') {
    return {
      ...base,
      countryFillMode: 'none',
      countryFillDefaultColor: '',
      countryFillDefaultOpacity: 0.18,
      countryLabels: false,
      labelMinScreenSize: 300,
      labelColor: '',
      labelHaloColor: 'rgba(0, 5, 12, 0.85)',
      labelFontWeight: '500',
      autoRotate: true,
      autoRotateSpeed: 0.045,
      axisTilt: 23.5,
      atmosphere: false,
      atmosphereColor: '',
      atmosphereIntensity: 0,
      atmosphereRadiusScale: 0,
      atmospherePower: 0,
      atmosphereThreshold: 0.6,
      atmosphereBlending: 'additive',
      starfield: true,
      starfieldDensity: 1800,
      starfieldSize: 1.1,
      starfieldMultiColor: true,
      starfieldPalette: ['#ffffff', '#d8ecff', '#9dc8ff', '#fff0b8', '#ffd36a'],
      focusPulseOrigin: 'click',
      focusPulseOnSurfaceClick: true,
      arcColor: '#f6b44d',
      arcWidth: 1.25,
      arcMinHeight: 0.18,
      arcMaxHeight: 0.72,
      arcPerArcGradient: true,
      markerDataset: 'megacities',
      markerColor: '#ffd36a',
      markerPerMarkerColor: false,
      markerSize: 0.85,
      markerHoverScale: 1.45,
      markerPulse: true,
      markerPulseAmplitude: 0.18,
      initialLat: 32,
      initialLng: -66,
      cinematicLightX: -0.68,
      cinematicLightY: 0.72,
      cinematicLightZ: 0.22,
      cinematicTerminatorSoftness: 0.34,
      cinematicTerminatorContrast: 1.58,
      cinematicKeyIntensity: 1.54,
      cinematicFillIntensity: 0.1,
      cinematicRimIntensity: 1.12,
      cinematicRimPower: 2.18,
      cinematicSpecularIntensity: 0.92,
      cinematicOceanSheen: 0.58,
      cinematicCityLights: false,
      cinematicCityLightIntensity: 1.62,
      cinematicCityLightCount: 11800,
      cinematicCityLightSize: 0.0056,
      cinematicNetwork: true,
      cinematicNetworkOpacity: 0.19,
      cinematicNetworkConnections: 58,
      cinematicQuality: 'auto',
      cinematicLightInfluence: 1,
      cinematicCameraInfluence: 1,
      cinematicDensityInfluence: 1,
      cinematicTerminatorBoost: 1.28,
      cinematicHorizonGlow: 1.34,
      cinematicAtmosphericScatter: 1.38,
      cinematicSurfaceMicroDetail: 1.22,
      cinematicCityNightResponse: 0,
      cinematicOrbitalFlow: 1.08,
      cinematicBorders: true,
    };
  }

  if (kind !== 'paper') return base;

  return {
    ...base,
    labelColor: '',
    labelHaloColor: 'rgba(91, 58, 31, 0.34)',
    labelFontWeight: '600',
    atmosphereBlending: 'normal',
    atmosphereIntensity: 0.42,
    atmosphereRadiusScale: 1.1,
    starfieldDensity: 520,
    starfieldSize: 1.1,
    starfieldMultiColor: true,
    starfieldPalette: ['#7a5a2c', '#bfa974', '#d99a35', '#8fc7b0', '#9fc5e8', '#d9a7c7'],
    countryFillMode: 'none',
    arcPerArcGradient: false,
    arcColor: '#7a4f2a',
    arcWidth: 1.25,
    arcMaxHeight: 0.32,
    markerPerMarkerColor: false,
    markerColor: '#a83a25',
    markerSize: 1.05,
    markerPulseAmplitude: 0.18,
    paperFillOpacity: 0.84,
    paperSurfaceWaterLines: 0.58,
    paperSurfaceWaterLineColor: '#567f80',
  };
};

export const defaultHeatmapSettings: HeatmapSettings = {
  dataset: 'countries',
  kernel: 'dome',
  normalize: 'absolute',
  curve: 'smoothstep',
  displacementCurve: 'cubic',
  palette: 'aurora',
  blendMode: 'normal',
  surfaceMode: 'country',
  detailMode: 'topo',
  radius: 0.075,
  maxHeight: 0.15,
  intensity: 1.6,
  threshold: 0.04,
  blurPasses: 1,
  shading: 0.74,
  meshLevel: 1,
  textureLevel: 1,
  domeCenterArea: 0.85,
  domeShoulderHeight: 0.83,
  domeEdgeSteepness: 1.4,
  domePreScale: 'log',
  animationEnabled: true,
  animationStyle: 'rise',
  animationOrder: 'sequential',
  animationEasing: 'ease-out-cubic',
  animationDurationMs: 1200,
  animationStaggerMs: 10,
  animationDelayMs: 0,
};

export const heatmapSurfacePresets: Readonly<Record<HeatmapSurfaceMode, Partial<HeatmapSettings>>> = {
  country: {
    dataset: 'countries',
    kernel: 'dome',
    normalize: 'absolute',
    curve: 'smoothstep',
    displacementCurve: 'cubic',
    palette: 'aurora',
    blendMode: 'normal',
    detailMode: 'topo',
    radius: 0.075,
    maxHeight: 0.15,
    intensity: 1.6,
    threshold: 0.04,
    blurPasses: 1,
    shading: 0.74,
    meshLevel: 1,
  },
  topographic: {
    kernel: 'gaussian',
    normalize: 'peak',
    curve: 'smoothstep',
    displacementCurve: 'smoothstep',
    palette: 'inferno',
    blendMode: 'normal',
    detailMode: 'topo',
    radius: 0.09,
    maxHeight: 0.12,
    intensity: 1.05,
    threshold: 0.04,
    blurPasses: 3,
    shading: 0.58,
    meshLevel: 1,
  },
  smooth: {
    kernel: 'gaussian',
    normalize: 'log',
    curve: 'sqrt',
    displacementCurve: 'sqrt',
    palette: 'aurora',
    blendMode: 'normal',
    detailMode: 'grid',
    radius: 0.17,
    maxHeight: 0.028,
    intensity: 0.96,
    threshold: 0,
    blurPasses: 5,
    shading: 0.22,
    meshLevel: 0,
  },
  peaks: {
    kernel: 'quartic',
    normalize: 'log',
    curve: 'cubic',
    displacementCurve: 'smoothstep',
    palette: 'inferno',
    blendMode: 'additive',
    detailMode: 'clean',
    radius: 0.055,
    maxHeight: 0.035,
    intensity: 1.45,
    threshold: 0.07,
    blurPasses: 1,
    shading: 0.15,
    meshLevel: 0,
  },
};

export const defaultState: ConfiguratorState = {
  activeLayer: 'none',
  lastPresetId: null,
  dirtySincePreset: false,
  globe: defaultGlobeSettings,
  heatmap: defaultHeatmapSettings,
  hexbin: {
    dataset: 'cluster',
    resolution: 3,
    aggregate: 'count',
    heightMax: 0.085,
    cellInset: 0.97,
    opacity: 0.94,
    showEmpty: true,
    borders: false,
    borderOpacity: 0.3,
    highlight: true,
    animationEnabled: true,
    animationStyle: 'rise',
    animationOrder: 'radial',
    animationEasing: 'ease-out-cubic',
    animationDurationMs: 1300,
    animationStaggerMs: 2.5,
  },
  charts: {
    dataset: 'energy',
    chartType: 'bars-grouped',
    size: 0.06,
    height: 0.1,
    innerRadius: 0.45,
    padAngle: 0.02,
    labels: 'hover',
    borders: false,
    highlight: true,
    animationEnabled: true,
    animationOrder: 'sequential',
    animationEasing: 'ease-out-back',
    animationDurationMs: 900,
    animationStaggerMs: 35,
    segmentStaggerMs: 60,
  },
};

const layerFromPath = (pathname: string): ActiveLayer => {
  if (pathname.includes('heatmap')) return 'heatmap';
  if (pathname.includes('charts')) return 'charts';
  if (pathname.includes('hexbin')) return 'hexbin';
  return 'none';
};

export const initialStateForPath = (pathname: string): ConfiguratorState => ({
  ...defaultState,
  activeLayer: layerFromPath(pathname),
});

export const configuratorPresets: ReadonlyArray<{
  readonly id: string;
  readonly label: string;
  readonly patch: Partial<ConfiguratorState>;
}> = [
  {
    id: 'hexbin-ops',
    label: 'Hexbin operations',
    patch: {
      activeLayer: 'hexbin',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline' },
      hexbin: { ...defaultState.hexbin, dataset: 'cluster', aggregate: 'count', resolution: 3 },
    },
  },
  {
    id: 'heatmap-population',
    label: 'Population relief',
    patch: {
      activeLayer: 'heatmap',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline', atmosphere: false },
      heatmap: { ...defaultHeatmapSettings, ...heatmapSurfacePresets.country, surfaceMode: 'country' },
    },
  },
  {
    id: 'charts-economy',
    label: 'Economy charts',
    patch: {
      activeLayer: 'charts',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline' },
      charts: {
        ...defaultState.charts,
        chartType: 'extruded',
        dataset: 'world-gdp',
        labels: 'off',
        animationOrder: 'value',
      },
    },
  },
  {
    id: 'hologram-sensors',
    label: 'Hologram sensors',
    patch: {
      activeLayer: 'hexbin',
      globe: {
        ...defaultGlobeSettings,
        kind: 'hologram',
        theme: 'hologram-cyan',
        atmosphere: true,
        starfield: true,
      },
      hexbin: { ...defaultState.hexbin, dataset: 'random-2k', aggregate: 'sum', showEmpty: false },
    },
  },
  {
    id: 'paper-learning-atlas',
    label: 'Paper learning atlas',
    patch: {
      activeLayer: 'none',
      globe: {
        ...defaultGlobeSettings,
        kind: 'paper',
        theme: 'paper-default',
        atmosphere: true,
        atmosphereBlending: 'normal',
        atmosphereIntensity: 0.45,
        starfield: true,
        starfieldDensity: 520,
        starfieldSize: 1.1,
        starfieldMultiColor: true,
        starfieldPalette: ['#7a5a2c', '#bfa974', '#d99a35', '#8fc7b0', '#9fc5e8', '#d9a7c7'],
        countryFillMode: 'none',
        countryFillDefaultOpacity: 0.42,
        countryFillPalette: ['#f6c56f', '#8fc7b0', '#9fc5e8', '#d9a7c7', '#b8d26f', '#f09a8a'],
        arcPerArcGradient: false,
        arcColor: '#7a4f2a',
        arcWidth: 1.25,
        arcMaxHeight: 0.32,
        markerPerMarkerColor: false,
        markerColor: '#a83a25',
        markerSize: 1.05,
        markerPulseAmplitude: 0.18,
        paperFillOpacity: 0.84,
        paperSurfaceWaterLines: 0.58,
        paperSurfaceWaterLineColor: '#567f80',
      },
    },
  },
];
