import { Kbd } from '@/components/shared/components/Kbd';
import { ApiTable, Callout, CodePanel, DocPage, DocSection, Step, Steps } from '@/components/docs';
import type { DocLocation } from '@/docs/manifest';
import { generateStudioCode } from '@/lib/studio-document-code';

const EXPORT_USE = {
  vanilla: generateStudioCode('vanilla'),
  react: generateStudioCode('react'),
  vue: generateStudioCode('vue'),
  angular: generateStudioCode('angular'),
};

export function StudioExport({ tab, group, page }: DocLocation) {
  return (
    <DocPage crumbs={[tab.label, group.label]} eyebrow={page.eyebrow} title={page.title} lead="Export code and runtime configuration for your app, or save an editable Studio project to continue later. Each has its own tab in the export dialog.">
      <DocSection title="Use it">
        <Steps>
          <Step title="Open Export">The <em>Take your globe with you</em> dialog opens on <em>Use in app</em>.</Step>
          <Step title="Choose your framework">Select Vanilla, React, Vue or Angular, then copy or download the generated code.</Step>
          <Step title="Save the companion config">Download <code>globe-config.json</code> into the same directory as the generated file. Enable <code>resolveJsonModule</code> in your TypeScript configuration.</Step>
        </Steps>
        <CodePanel code={EXPORT_USE} caption="These examples are generated by the same code as Studio. Keep the companion JSON next to the file." />
        <Callout tone="note">
          A globe needs a container with an explicit height. The generated examples include sizing and release the engine when their component or page unmounts.
        </Callout>
      </DocSection>
      <DocSection title="What is inside">
        <ul>
          <li>
            <code>globe</code> — a full <code>GlobeConfig</code> minus <code>container</code>, including the kind section and the theme selected in Studio.
          </li>
          <li>
            <code>dataLayer</code> — the active <code>DataLayer</code> with its dataset, or <code>null</code>.
          </li>
        </ul>
        <p>Custom themes are exported as inline tokens so they work outside this browser. The runtime file contains data and configuration; it does not contain event handlers, DOM elements or functions.</p>
        <Callout tone="note">Cinematic scenes can reference Earth textures. Copy the demo&apos;s <code>public/textures/earth</code> directory to the same path in your app, or provide your own texture URLs. Package names shown in this workspace are still <code>@globiojs/*</code>; package publishing is separate from the export workflow.</Callout>
      </DocSection>
      <DocSection title="Save an editable project">
        <p>In the export dialog, choose <em>Studio project</em> and <em>Save project</em>. The project records all Studio controls, the active custom theme and its tokens, and the loaded heatmap snapshot. It can be opened in another browser without recreating your settings.</p>
        <Steps>
          <Step title="Open project">Use the <em>Open project</em> action in the top bar or command palette.</Step>
          <Step title="Choose or paste JSON">Select a saved Studio project file, or paste its JSON into the text field.</Step>
          <Step title="Review project">Check the kind, theme and data summary before choosing <em>Open project</em> to apply it.</Step>
        </Steps>
        <Callout tone="note">Older runtime exports with only <code>globe</code> and <code>dataLayer</code> do not preserve every Studio control and cannot be reopened as projects. They remain usable in your application. Save the <em>Studio project</em> format when you want to keep editing.</Callout>
      </DocSection>
    </DocPage>
  );
}

export function StudioPresets({ tab, group, page }: DocLocation) {
  return (
    <DocPage crumbs={[tab.label, group.label]} eyebrow={page.eyebrow} title={page.title} lead="Presets are complete Studio states per kind. Built-in ones ship with the demo; your own are saved in this browser's storage and appear next to them.">
      <DocSection title="Apply a preset">
        <Steps>
          <Step title="Choose a preset">Use the preset selector in the top bar to browse built-in scenes and your saved presets.</Step>
          <Step title="Apply it">The main globe takes the preset&apos;s config; every panel updates to match.</Step>
          <Step title="Or use the palette">
            <Kbd>⌘</Kbd>
            <Kbd>K</Kbd> then type the preset name; custom presets are listed with a <em>(custom)</em> suffix.
          </Step>
        </Steps>
      </DocSection>
      <DocSection title="Save your own">
        <p>
          <em>Save preset</em> stores the current state under a name; <em>Manage saved themes &amp; presets</em> lists, renames and deletes them. Both live in{' '}
          <code>localStorage</code>, so they stay on this machine and browser.
        </p>
        <Callout tone="tip">
          To move the active scene to another machine, choose <em>Export → Studio project → Save project</em>. Use <em>Open project</em> in the other browser, review it, then save a new local preset if you want it in that browser&apos;s preset list.
        </Callout>
      </DocSection>
    </DocPage>
  );
}

const ACTIONS = [
  { action: 'Replay layer animation', chip: 'R', what: 'Runs the active data layer\'s mount animation again.' },
  { action: 'Reset camera to home view', chip: 'H', what: 'Back to the initial position and distance.' },
  { action: 'Manage saved themes & presets', chip: '', what: 'Opens the list of items saved in this browser.' },
  { action: 'Export code, config or Studio project', chip: 'E', what: 'Opens framework code, runtime JSON and editable project downloads.' },
  { action: 'Open a Studio project', chip: '', what: 'Validates a project file or pasted JSON before applying it.' },
  { action: 'Reset configurator (reload)', chip: '', what: 'Discards the session and reloads the Studio.' },
];

export function StudioShortcuts({ tab, group, page }: DocLocation) {
  return (
    <DocPage crumbs={[tab.label, group.label]} eyebrow={page.eyebrow} title={page.title} lead="One chord opens the palette; everything else is a search away. The chips next to quick actions show their letter inside the palette.">
      <DocSection title="Open the palette">
        <p>
          <Kbd>⌘</Kbd>
          <Kbd>K</Kbd> on macOS, <Kbd>Ctrl</Kbd>
          <Kbd>K</Kbd> elsewhere. Type to filter; groups are Quick actions, Switch kind, Themes for the active kind, and Apply preset.
        </p>
      </DocSection>
      <DocSection title="Quick actions">
        <ApiTable
          columns={[
            { key: 'action', label: 'Action', className: 'docs-col-name' },
            { key: 'chip', label: 'Chip' },
            { key: 'what', label: 'What it does' },
          ]}
          rows={ACTIONS.map((a) => ({
            id: `action-${a.chip || a.action.toLowerCase().replace(/[^a-z]+/g, '-')}`,
            cells: { action: a.action, chip: a.chip ? <Kbd>{a.chip}</Kbd> : <span className="docs-dash">—</span>, what: a.what },
          }))}
        />
        <Callout tone="note">The action chips are labels, not global single-letter shortcuts. Use the command palette or the corresponding top-bar controls.</Callout>
      </DocSection>
    </DocPage>
  );
}
