import type { FeatureDoc } from './types';

export const APPEARANCE_FEATURES: ReadonlyArray<FeatureDoc> = [
  {
    id: 'theme',
    title: 'Theme',
    configPaths: ['theme'],
    summary: 'A preset name or custom token overrides. Theme tokens supply renderer defaults; supported per-instance options take precedence.',
    kinds: 'all',
    docs: { slug: 'appearance/themes' },
    related: ['theme-tokens', 'kind'],
  },
  {
    id: 'theme-tokens',
    title: 'Theme tokens',
    summary: 'The flat, typed token set behind every theme: background, surface, borders, fills, dots, labels, tooltip, atmosphere, starfield, arcs and legend.',
    kinds: 'all',
    docs: { slug: 'appearance/tokens' },
    related: ['theme'],
  },
  {
    id: 'atmosphere',
    tip: () => import('./tips/AtmosphereShapeTip'),
    title: 'Atmosphere',
    configPaths: ['atmosphere'],
    summary: 'The Fresnel rim glow around the globe: colour, intensity, radius, softness, which side it renders on and an optional slow pulse.',
    kinds: 'all',
    docs: { slug: 'appearance/atmosphere', anchor: 'atmosphere' },
    related: ['starfield', 'transparent-canvas'],
  },
  {
    id: 'starfield',
    title: 'Starfield',
    configPaths: ['starfield'],
    summary: 'Background stars: density, size, palette, size variety, optional twinkle and, on the cinematic kind, the Milky Way band.',
    kinds: 'all',
    docs: { slug: 'appearance/atmosphere', anchor: 'starfield' },
    related: ['atmosphere'],
  },
  {
    id: 'transparent-canvas',
    title: 'Transparent canvas',
    configPaths: ['transparent'],
    summary: 'Let the page background show through instead of the theme background colour. For globes used as decoration over gradients or images.',
    kinds: 'all',
    docs: { slug: 'appearance/atmosphere', anchor: 'background' },
    related: ['framing'],
  },
  {
    id: 'countries',
    title: 'Countries',
    configPaths: ['countries'],
    summary: 'The country layer: which geometry loads, whether hover picks, and how borders and fills are styled per instance.',
    kinds: 'all',
    docs: { slug: 'appearance/countries' },
    related: ['countries-resolution', 'country-borders', 'country-fill', 'country-hover'],
  },
  {
    id: 'countries-resolution',
    tip: () => import('./tips/ResolutionTip'),
    title: 'Country resolution',
    configPaths: ['countries.resolution'],
    summary: 'Which country geometry loads: low, medium or high. Decides download size, build time and border fidelity.',
    kinds: 'all',
    docs: { slug: 'appearance/countries', anchor: 'resolution' },
    related: ['performance'],
  },
  {
    id: 'country-borders',
    title: 'Border styling',
    configPaths: ['countries.borderHover', 'countries.borderActive'],
    summary: 'Per-instance overrides for the hovered and the active country stroke: colour, width, opacity and the additive glow behind the hover.',
    kinds: ['outline', 'paper', 'cinematic', 'hologram'],
    docs: { slug: 'appearance/countries', anchor: 'borders' },
    related: ['country-hover', 'active-country'],
  },
  {
    id: 'country-fill',
    tip: () => import('./tips/FillModesTip'),
    title: 'Country fills',
    configPaths: ['countries.fill'],
    summary: 'Solid fills under the borders: hidden, a single colour for every country, a palette by index, or driven by data.',
    kinds: ['outline', 'dotted', 'cinematic'],
    docs: { slug: 'appearance/countries', anchor: 'fills' },
    related: ['country-data'],
  },
  {
    id: 'postprocessing',
    title: 'Post-processing',
    configPaths: ['postprocessing'],
    summary: 'The shared HDR pipeline: bloom, anamorphic streak, vignette, chromatic aberration, film grain and exposure. On by default for the cinematic kind only.',
    kinds: ['cinematic', 'hologram', 'outline', 'dotted', 'wireframe', 'paper'],
    docs: { slug: 'appearance/postprocessing' },
    related: ['kind-cinematic'],
  },
];
