import type { FeatureDoc } from './types';
import { EVENTS } from '../snippets';

export const INTERACTION_FEATURES: ReadonlyArray<FeatureDoc> = [
  {
    id: 'events',
    title: 'Events',
    methods: ['on', 'off'],
    events: ['countryClick', 'countryHover', 'ready', 'error'],
    summary: 'Subscribe by name; every handler gets a typed payload and on() returns the unsubscribe function. The wrappers expose the same events as callbacks.',
    kinds: 'all',
    docs: { slug: 'interaction/events' },
    example: EVENTS,
    related: ['surface-click', 'story'],
  },
  {
    id: 'surface-click',
    title: 'Surface clicks',
    events: ['surfaceClick'],
    summary: 'A click on the globe that hit no country, with the lat/lng under the pointer. Never fires together with countryClick.',
    kinds: 'all',
    docs: { slug: 'interaction/events', anchor: 'surface-clicks' },
    related: ['events', 'fly-to'],
  },
  {
    id: 'country-hover',
    tip: () => import('./tips/HoverOccludeTip'),
    title: 'Hover',
    configPaths: ['countries.hoverEnabled', 'countries.hoverOccludeBackSide'],
    summary: 'Pointer hover over countries: on by default, with the far side of a country hidden unless you want the x-ray look.',
    kinds: ['outline', 'dotted', 'cinematic', 'hologram', 'paper'],
    docs: { slug: 'interaction/selection', anchor: 'hover' },
    related: ['country-borders', 'active-country'],
  },
  {
    id: 'hover-crosshair',
    title: 'Hover crosshair',
    configPaths: ['outline.hoverCrosshair'],
    summary: 'Latitude and longitude guide lines follow the hovered country or pointer. Configured under outline on every supported kind.',
    kinds: ['outline', 'dotted', 'hologram', 'cinematic', 'paper'],
    docs: { slug: 'interaction/selection', anchor: 'crosshair' },
    related: ['country-hover', 'initial-position'],
  },
  {
    id: 'active-country',
    title: 'Active country',
    methods: ['setActiveCountry', 'getActiveCountry'],
    summary: 'Pin one country as selected; it keeps its highlight after the pointer leaves and stories can set it per scene.',
    kinds: 'all',
    docs: { slug: 'interaction/selection', anchor: 'active-country' },
    related: ['focus-on-country', 'country-borders'],
  },
  {
    id: 'focus-pulse',
    tip: () => import('./tips/FocusPulseTip'),
    title: 'Focus pulse',
    configPaths: ['focusPulse'],
    summary: 'The ring that fires when a country is focused: from its centroid or the clicked point, optionally on any surface click. Each kind draws its own.',
    kinds: 'all',
    docs: { slug: 'interaction/selection', anchor: 'focus-pulse' },
    related: ['focus-on-country', 'surface-click'],
  },
  {
    id: 'projection',
    title: 'Projection',
    methods: ['project'],
    summary: 'Turn a lat/lng into canvas pixels for your own overlays. Returns null when the point is on the far side or outside the canvas.',
    kinds: 'all',
    docs: { slug: 'interaction/projection' },
    related: ['html-markers'],
  },
  {
    id: 'export-image',
    title: 'Export to image',
    methods: ['toImage'],
    summary: 'A PNG data URL of the current WebGL frame, optionally at another size. Capture thumbnails and snapshots in a browser.',
    kinds: 'all',
    docs: { slug: 'interaction/projection', anchor: 'export' },
  },
];
