import type { FeatureDoc } from './types';
import { kindSnippet } from '../snippets';

export const KIND_FEATURES: ReadonlyArray<FeatureDoc> = [
  {
    id: 'kind',
    title: 'Kind',
    configPaths: ['kind'],
    summary: 'Which renderer draws the globe. Six kinds share one API; create a new instance to switch kind. Studio handles this rebuild for you.',
    kinds: 'all',
    docs: { slug: 'start/choosing-a-kind' },
    example: kindSnippet('outline', 'outline-dark'),
    related: ['theme'],
  },
  {
    id: 'mode',
    title: 'Mode',
    configPaths: ['mode'],
    summary: 'Projection of the scene. Only the sphere is rendered today; the flat value is reserved for a future map view.',
    kinds: 'all',
    docs: { slug: 'api/globe-config', anchor: 'identity' },
  },
  {
    id: 'kind-cinematic',
    title: 'Cinematic kind',
    configPaths: ['cinematic'],
    summary: 'A filmic Earth: procedural relief and biomes, clouds with shadows, a scattering atmosphere, a sun you can pin, orbit or sync to real time.',
    kinds: ['cinematic'],
    docs: { slug: 'kinds/cinematic' },
    example: kindSnippet('cinematic', 'cinematic-night'),
    related: ['postprocessing', 'cinematic-data'],
  },
  {
    id: 'cinematic-sun',
    title: 'Cinematic sun',
    configPaths: ['cinematic.sun'],
    summary: 'Set a fixed light direction, animate its orbit, or derive its position from UTC time to move the day/night boundary.',
    kinds: ['cinematic'],
    docs: { slug: 'kinds/cinematic', anchor: 'sun' },
    tip: () => import('./tips/SunModesTip'),
    related: ['kind-cinematic', 'cinematic-data'],
  },
  {
    id: 'kind-outline',
    title: 'Outline kind',
    configPaths: ['outline'],
    summary: 'Crisp borders on a deep sea with hover and active states, a lat/lng crosshair and a focus pulse. The default.',
    kinds: ['outline'],
    docs: { slug: 'kinds/outline' },
    example: kindSnippet('outline', 'outline-cyber'),
    related: ['country-borders', 'country-fill'],
  },
  {
    id: 'kind-dotted',
    title: 'Dotted kind',
    configPaths: ['dotted'],
    summary: 'Continents as dot fields with ripples and hover effects. Choropleth data colours the country fills behind the dots.',
    kinds: ['dotted'],
    docs: { slug: 'kinds/dotted' },
    example: kindSnippet('dotted', 'dotted-dark'),
    related: ['country-data'],
  },
  {
    id: 'kind-wireframe',
    title: 'Wireframe kind',
    configPaths: ['wireframe'],
    summary: 'A latitude and longitude grid over a translucent shell with pulses, data packets and streams. No country linework.',
    kinds: ['wireframe'],
    docs: { slug: 'kinds/wireframe' },
    example: kindSnippet('wireframe', 'wireframe-tron'),
  },
  {
    id: 'kind-hologram',
    title: 'Hologram kind',
    configPaths: ['hologram'],
    summary: 'A projection that never sits still: scanlines, a fresnel rim, chromatic aberration and a shimmer sweep.',
    kinds: ['hologram'],
    docs: { slug: 'kinds/hologram' },
    example: kindSnippet('hologram', 'hologram-cyan'),
  },
  {
    id: 'kind-paper',
    title: 'Paper kind',
    configPaths: ['paper'],
    summary: 'Ink on grain: a parchment surface with rough borders, vignette, aging marks and atlas-style labels.',
    kinds: ['paper'],
    docs: { slug: 'kinds/paper' },
    example: kindSnippet('paper', 'paper-default'),
    related: ['country-labels'],
  },
];
