import type { FeatureDoc } from './types';
import { QUICK_START } from '../snippets';

export const RUNTIME_FEATURES: ReadonlyArray<FeatureDoc> = [
  {
    id: 'lifecycle',
    title: 'Lifecycle',
    methods: ['mount', 'destroy', 'update', 'resize', 'getCanvas'],
    summary: 'Create the scene, mount the canvas, patch the running config with update(), destroy when the element leaves. resize() re-measures after a CSS change.',
    kinds: 'all',
    docs: { slug: 'api/create-globe' },
    example: QUICK_START,
    related: ['pausing', 'performance'],
  },
  {
    id: 'story',
    title: 'Story engine',
    methods: ['setStory', 'playStory', 'pauseStory', 'nextScene', 'prevScene', 'goToScene', 'getCurrentScene', 'isStoryPlaying'],
    events: ['sceneEnter', 'sceneExit', 'storyComplete'],
    summary: 'Declarative scenes with camera moves, a highlighted country and a popup, auto-advancing on a timeline with play, pause and jump controls.',
    kinds: 'all',
    docs: { slug: 'story/engine' },
    related: ['fly-to', 'focus-on-country', 'active-country'],
  },
  {
    id: 'performance',
    tip: () => import('./tips/PixelRatioTip'),
    title: 'Performance settings',
    configPaths: ['performance'],
    summary: 'Antialiasing, pixel ratio, a per-globe frame-rate ceiling and adaptive quality that lowers the pixel ratio on slow frames.',
    kinds: 'all',
    docs: { slug: 'performance/overview' },
    related: ['pausing', 'countries-resolution', 'timing-marks'],
  },
  {
    id: 'pausing',
    tip: () => import('./tips/PausingTip'),
    title: 'Pausing',
    configPaths: ['performance.pauseWhenHidden'],
    methods: ['setPaused'],
    summary: 'Off-screen and hidden-tab globes stop rendering on their own; setPaused() keeps a globe warm behind a cross-fade without spending frames.',
    kinds: 'all',
    docs: { slug: 'performance/pausing' },
    related: ['performance'],
  },
  {
    id: 'timing-marks',
    title: 'Timing marks',
    summary: 'User Timing measures for construction, country loading, kind build, shader compile and mount-to-ready. Read them in DevTools or with the Performance API.',
    kinds: 'all',
    docs: { slug: 'performance/timing' },
    related: ['performance'],
  },
  {
    id: 'country-ids',
    title: 'Country ids',
    summary: 'Built-in countries use three-digit numeric ISO ids. Short numeric strings are padded automatically; use normalizeCountryId() to convert a number.',
    kinds: 'all',
    docs: { slug: 'api/country-ids' },
    related: ['country-data'],
  },
  {
    id: 'studio-presets',
    title: 'Studio presets',
    summary: 'Complete Studio states per kind: the built-in ones ship with the demo, yours are saved in this browser and listed next to them.',
    kinds: 'all',
    docs: { slug: 'studio/presets' },
    related: ['theme', 'kind'],
  },
  {
    id: 'wrapper-react',
    title: 'React wrapper',
    summary: 'A <Globe /> component: every config key is a prop, every event an on* callback, and the ref handle reaches the instance.',
    kinds: 'all',
    docs: { slug: 'frameworks/react' },
    related: ['lifecycle'],
  },
  {
    id: 'wrapper-vue',
    title: 'Vue wrapper',
    summary: '<VueGlobe /> with kebab-case props for every config key, emits for every event and getInstance() on the component ref.',
    kinds: 'all',
    docs: { slug: 'frameworks/vue' },
    related: ['lifecycle'],
  },
  {
    id: 'wrapper-angular',
    title: 'Angular wrapper',
    summary: 'A standalone <ng-globe> with an input per config key, an output per event and getInstance() on the component. Runs outside the zone.',
    kinds: 'all',
    docs: { slug: 'frameworks/angular' },
    related: ['lifecycle'],
  },
];
